//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLandRIESGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POLandRIESGOS()
        {
            this.PRDR = new HashSet<PRDR>();
        }
    
        public int Id_Hallazgos { get; set; }
        public string Nombre_Hallazgo { get; set; }
        public string Descripcion_Hallazgo { get; set; }
        public System.DateTime Fecha_Hallazgo { get; set; }
        public int Id_Politica { get; set; }
        public int Id_Riesgo { get; set; }
        public byte[] Path_Hallazgo { get; set; }
    
        public virtual POLITICAS POLITICAS { get; set; }
        public virtual RIESGOS RIESGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRDR> PRDR { get; set; }
    }
}
