//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLITICAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POLITICAS()
        {
            this.POLandRIESGOS = new HashSet<POLandRIESGOS>();
        }
    
        public int Id_Politica { get; set; }
        public string Nombre_Politica { get; set; }
        public string Descripcion_Politica { get; set; }
        public string Funcion_Politica { get; set; }
        public string Categoria_Politica { get; set; }
        public string SubCategoria_Politica { get; set; }
        public string Referencia_Politica { get; set; }
        public string Path_Politica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLandRIESGOS> POLandRIESGOS { get; set; }
    }
}
