//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDR
    {
        public int Id_PRDR { get; set; }
        public string Nombre_Requirimiento { get; set; }
        public string Nombre_Documento { get; set; }
        public string Nombre_Hallazgo { get; set; }
        public int Id_Hallazgo { get; set; }
        public int Id_Proyecto { get; set; }
        public int Id_Requerimiento { get; set; }
        public string Path_Documento { get; set; }
    
        public virtual POLandRIESGOS POLandRIESGOS { get; set; }
        public virtual REQandDOC REQandDOC { get; set; }
        public virtual REQUERIMIENTOS REQUERIMIENTOS { get; set; }
    }
}
