//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQandDOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQandDOC()
        {
            this.PRDR = new HashSet<PRDR>();
        }
    
        public int Id_Proyecto { get; set; }
        public int Id_Requerimiento { get; set; }
        public int Id_Documento { get; set; }
        public string Nombre_Requerimiento { get; set; }
        public string Nombre_Documento { get; set; }
    
        public virtual DOCUMENTOS DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRDR> PRDR { get; set; }
        public virtual REQUERIMIENTOS REQUERIMIENTOS { get; set; }
    }
}
