//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIESGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIESGOS()
        {
            this.POLandRIESGOS = new HashSet<POLandRIESGOS>();
        }
    
        public int Id_Riesgo { get; set; }
        public string Nombre_Riesgo { get; set; }
        public string Tipo_Riesgo { get; set; }
        public int Nivel_Riesgo { get; set; }
        public string Descripcion_Riesgo { get; set; }
        public string Categoria_Riesgo { get; set; }
        public string SubCategoria_Riesgo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLandRIESGOS> POLandRIESGOS { get; set; }
    }
}
