//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROandDOCEntities : DbContext
    {
        public PROandDOCEntities()
            : base("name=PROandDOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual DbSet<POLandRIESGOS> POLandRIESGOS { get; set; }
        public virtual DbSet<POLITICAS> POLITICAS { get; set; }
        public virtual DbSet<PRDR> PRDR { get; set; }
        public virtual DbSet<REQandDOC> REQandDOC { get; set; }
        public virtual DbSet<REQUERIMIENTOS> REQUERIMIENTOS { get; set; }
        public virtual DbSet<RIESGOS> RIESGOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AtencionRequerimiento> AtencionRequerimiento { get; set; }
    }
}
