//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUser { get; set; }
        public string nomUser { get; set; }
        public string emailUser { get; set; }
        public System.DateTime fechaUser { get; set; }
        public string passUser { get; set; }
        public System.DateTime fechapassUser { get; set; }
        public int idRol { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
